bio-routing/bio-rd

routingtable/locRIB/loc_rib.go, routingtable/locRIB/loc_rib_test.go
We do not need to update any clients or select new best paths
=> Return early if route is not present.

routingtable/client_manager.go
Release lock after updating map. UpdateNewClients may call GetOptions or Clients() and thus cause a deadlock.
=> Fix: Deadlock in locRIB

protocols/bgp/server/fsm.go, protocols/bgp/server/peer.go, protocols/bgp/server/server.go, routingtable/adjRIBIn/adj_rib_in_test.go, routingtable/client_interface.go, routingtable/client_manager_test.go, routingtable/filter/term_condition.go, routingtable/filter/term_condition_test.go, routingtable/locRIB/loc_rib.go
This patch allows a user to inject a Filter with LocRIB as backend into the FSM. I used it to create a locRIB which reject all announced prefixes from the adjRIBIN.
=> Feature: allow users to use filters infront of loc rib

protocols/bgp/packet/community.go, protocols/bgp/server/fsm.go, routingtable/adjRIBOut/adj_rib_out.go, routingtable/adjRIBOutAddPath/adj_rib_out_add_path.go, routingtable/neighbor.go, routingtable/update_helper.go, routingtable/update_helper_test.go
* added basic filtering for RFC1997 well known communities
For now it is placed in AdjRIBOut. I think after we get the filter implementation with the new FSM done, it should be moved in front of the custom filters
=> basic rfc1997 (well known communities) filter, code deduplication

AUTHORS, CONTRIBUTORS, config/server.go, main.go, protocols/bgp/server/BUILD.bazel, protocols/bgp/server/fsm2.go, protocols/bgp/server/peer.go, protocols/bgp/server/server.go, protocols/bgp/server/server_test.go
These will be consumed by a gRPC service. The server has a public
interface that returns basic information, and a snapshotted list of peer
status/info.
Also some small drive-by fixes.
=> Begin implementing public interface for server/peer info 

routingtable/BUILD.bazel, routingtable/adjRIBIn/adj_rib_in_test.go, routingtable/mock_client.go
Signed-off-by: Maximilian Wilhelm <max@sdn.clinic>
=> Moved RTMockClient into routingtable package to make it reusable.

route/route.go, routingtable/adjRIBOut/BUILD.bazel, routingtable/adjRIBOut/adj_rib_out.go, routingtable/adjRIBOut/adj_rib_out_test.go
- Remove all path for a prefix from an AddPath capabale neighbor if a path with NO_EXPORT/NO_ADVERTISE shows up.
- Add Route.NewRouteAddPath(pfx net.Prefix, p []*Path)
- Add a whole bunch of tests for AdjRIBOut.
=> Fix AdjRIBOut with AddPath and add whole bunch of tests of AdjRIBOut

protocols/bgp/server/fsm_established.go
local address was always 16 bytes which lead to invalid updates for non ipv6 eBGP sessions
=> Fix for eBGP Next-Hop Parsing

.circleci/check-gofmt, .circleci/config.yml, examples/bgp/main_ipv6.go, examples/netlink/main_ipv6.go, protocols/bgp/packet/encoder_test.go, protocols/bgp/server/bmp_router_test.go, protocols/bgp/server/bmp_server_test.go, protocols/bgp/server/fsm_address_family_test.go, protocols/bgp/server/fsm_open_sent_test.go, protocols/bgp/server/fsm_test.go, route/bgp_test.go, route/route_test.go, routingtable/adjRIBIn/adj_rib_in_test.go, routingtable/adjRIBOut/adj_rib_out_test.go, routingtable/client_manager_test.go, routingtable/contributing_asn_list.go, routingtable/filter/actions/add_large_community_action_test.go, routingtable/filter/term_condition_test.go
Go Report Card also runs `gofmt -s` to enable simplifications.
=> Apply gofmt and add check for CI

protocols/bgp/metrics/bgp_peer_metrics.go, protocols/bgp/server/metrics_service.go, protocols/bgp/server/metrics_service_test.go
This enables users of the bio-rd library to reuse the state numbering.
Otherwise users have to maintain their own constats to avoid magic
numbers.
=> Move fsm state number constants to metrics package.

protocols/bgp/server/fsm.go
Fixes:
```
INFO[0000] FSM: Neighbor state change                    last_state=openConfirm new_state=established peer=10.80.200.135 reason="Received KEEPALIVE"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12354]
goroutine 51 [running]:
runtime/internal/atomic.goXadd64(0x29a20d4, 0x1, 0x0, 0x0, 0x406ad0)
/usr/lib/go-1.11/src/runtime/internal/atomic/atomic_arm.go:96 +0x1c
github.com/bio-routing/bio-rd/protocols/bgp/server.(*establishedState).update(0x2995e9c, 0x2926f20, 0x2884c90, 0x0, 0x0, 0x8e0f8)
/home/pi/bio-rd/protocols/bgp/server/fsm_established.go:200 +0x3c
github.com/bio-routing/bio-rd/protocols/bgp/server.(*establishedState).msgReceived(0x2995e9c, 0x29b6000, 0x1000, 0x1000, 0x2995df8, 0xc, …
```
=> Fix alignment issue on arm

protocols/bgp/packet/helper.go
This change is here to validate received prefixes.
We had issues using BIO as a BMP receiver with a JUNOS bug that caused BGP add path NLRIs to be interpreted without taking the add path ID into account. Thus IDs have been interpreted as NLRIs causing invalid prefixes to end up in tables. In these cases I think decoding should fail if it's evident something completely invalid happens here.
=> BGP: Validate NLRI (valid Prefix)

go.sum, metrics/bgp/adapter/prom/bgp_prom_adapter.go, metrics/bmp/adapter/prom/bmp_prom_adapter.go, metrics/vrf/adapter/prom/vrf_prom_adapter.go, protocols/bgp/metrics/bmp_metrics.go, protocols/bgp/server/bmp_metrics_service.go
Currently metrics are identified by their "router=XXX" label. Unfortunately while a BMP session is down that value is the empty string. When multiple BMP sessions are not established the prometheus library fails to expose the metrics because of metrics duplicates. I'm adding the "agent_address" label here und change the "router" label to "sys_name" to make clear that names comes from the BMP Init message.
=> Fix BMP label names/combinations

protocols/bgp/packet/bgp.go, protocols/bgp/packet/decoder.go, protocols/bgp/packet/decoder_test.go
I've tested this stuff with FRR-7.3. FRR sends out ConnectionCollisionResolution and OtherConfigChange in my tests, bio wasn't to happy about it, but now it looks good.
=> Accept all rfc4486 bgp error codes

protocols/bgp/packet/mp_reach_nlri.go, protocols/bgp/packet/path_attributes_test.go
RFC2545 section 3 paragraph 2 allows for a next-hop field length of 32.
In this case two IPv6 addresses are being sent, first the global
address, then the link local address. For now we are just ignoring the
link local address and parsing only the first.
Without this patch Bio will not be able to talk to BGP spekaders using
this features. An UPDATE mesage containing such a next-hop field would
result in the following error:
Failed to decode BGP message: Failed to decode message: Unable to decode path attr: Failed to multi protocol reachable NLRI: Unable to decode MP_REACH_NLRI: Failed to decode next hop IP: byte slice has an invalid length. Expected either 4 (IPv4) or 16 (IPv6) bytes but got: 32
=> Handle multiple next-hops in NLRI

protocols/bgp/packet/decoder.go, protocols/bgp/packet/decoder_test.go, protocols/bgp/packet/encoder_test.go, protocols/bgp/packet/parameters.go, protocols/bgp/server/bmp_router.go, protocols/bgp/server/fsm_open_sent.go, protocols/bgp/server/fsm_open_sent_test.go, protocols/bgp/server/peer.go
RFC7911 sec 4 allows multiple AFISAFIs in a single AddPath capability
entry, which also must be presented in a single capability message.
Without this patch the AddPath capability of a peer advertising multiple
AFISAFIs cannot be parsed and the connection will fail.
=> Allow multiple AFISAFIs in AddPath capability

routingtable/adjRIBIn/adj_rib_in.go
If addpath is enabled rx then `adjRIBIn.RemovePath()` will access a member
of p. As p might be nil (e.g. called by `fsm_address_family withdraw()`)
we need to check for this before accessing it.
---
Test missing, input on that would be welcome. Also I'm not sure if this is the right way to fix this or if there would be a point before this were we'd need to handle this.
For reference, here is the stacktrace I got:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x922412]
goroutine 9 [running]:
github.com/bio-routing/bio-rd/routingtable/adjRIBIn.(*AdjRIBIn).removePath(0xc000d105a0, 0xc000b888a0, 0x0, 0xc000a42001)
/home/seba/projects/src/bio-rd/routingtable/adjRIBIn/adj_rib_in.go:240 +0x242 …
```
=> Fix crash on route withdrawal with addpath

cmd/ris/risserver/rib_client.go, cmd/ris/risserver/server.go, protocols/bgp/server/bmp_router.go, protocols/bgp/server/update_sender.go, protocols/kernel/kernel.go, routingtable/adjRIBOut/adj_rib_out.go, routingtable/client_interface.go, routingtable/client_manager_test.go, routingtable/locRIB/loc_rib.go, routingtable/mock_client.go, routingtable/vrf/vrf_registry.go
Background: After a router went down all routes have been withdrawn as expected to all clients currently running the ObserveRIB gRPC. However, the BMP server creates fresh VRFs and RIBs when a BMP session comes back up.
Thus the running ObserveRIB calls were using stale RIB references and in the end not sending any new routes received via BMP to the running ObserveRIB clients. It is better to just detect this situation and end the RPC so clients can reconnect and get information from the current RIB.
=> Tear down ObserveRIB streaming RPC when RIB is destroyed

protocols/bgp/types/as_path.go, protocols/bgp/types/as_path_test.go
Adds test for `protocols/bgp/types/as_path.go`. The `String()` function of `ASPath` was re-implemented because its output was broken: sometimes spaces were missing, or in case it only contained one segment of type `ASSet`, it used to generate a leading space.
The rewrite of the `String` func was reviewed by @taktv6.
=> Add test for as_path.go + repair String()

net/tcp/listen.go, net/tcp/md5sig.go, net/tcp/tcp.go, net/tcp/tcpsock_posix.go
Also, use Standard error wrapping. SOL_IP and SOL_IPV6 are defined in tcp.go to allow compilation under Darwin.
See https://pkg.go.dev/syscall
=> Migrate to sys/unix, since usage of syscall is not recommended

.github/workflows/linter.yml
Found here: https://github.com/actions/checkout/issues/455#issuecomment-792228083
=> allow forks to be linted

protocols/bgp/server/bmp_server.go
Querying for unknown routers caused a nil pointer dereference.
=> add nil pointer check for validating connection

protocols/bgp/server/bmp_router.go
Otherwise the localASN stays at 23456 and BGPPathA.EBGP is incorrectly reported as external for all routes.
=> bmp: set local ASN to number from capability in case of ASN4

protocols/bgp/server/bgp_api.go, protocols/bgp/server/bmp_metrics_service.go, protocols/bgp/server/bmp_neighbor_manager.go, protocols/bgp/server/bmp_router.go, protocols/bgp/server/bmp_server.go, protocols/bgp/server/fsm.go, protocols/bgp/server/fsm_test.go, protocols/bgp/server/peer.go, protocols/bgp/server/server.go, protocols/bgp/server/update_helper.go, protocols/bgp/server/update_helper_test.go, protocols/bgp/server/update_sender.go
* Make sure error messages starting lower case
* Consolidate double imports
* Remove redundant return/fmt.Sprintf calls
* Remove unused variables from tests
=> Fix a number of go-staticcheck nits

protocols/bgp/server/fsm_address_family.go, routingtable/adjRIBIn/adj_rib_in.go, routingtable/adjRIBIn/adj_rib_in_test.go
RFC7911 sec 5 par 1 sais that the path identifier added by BGP Add Path
uniquely identifies a path for a given prefix. Therefore, when a new
path arrives we need to replace all paths with the same path identifier
for this prefix. Ignoring this leads to routes piling up in the
adjRIBIn.
=> Replace paths with same identifier with AddPath

cmd/ris/main.go, examples/bmp/main_bmp.go, protocols/bgp/server/bmp_server.go, protocols/bgp/server/bmp_server_test.go
Make sure a BMP peer is only added once, and we purge dynamic peers which went away with sending an init message.
=> Improve BMP peer handling for dynamci peers

protocols/bgp/server/bgp_api_test.go, protocols/bgp/server/fsm_address_family.go, protocols/bgp/server/fsm_address_family_test.go, protocols/bgp/server/fsm_established.go, protocols/bgp/server/peer.go, routingtable/adjRIBIn/adj_rib_in.go, routingtable/adjRIBIn/adj_rib_in_test.go, routingtable/adjRIBOut/adj_rib_out.go, routingtable/adjRIBOut/adj_rib_out_test.go, routingtable/adjRIBOut/path_id_manager.go, routingtable/client_manager_test.go, routingtable/mock_client.go, routingtable/session_attrs.go, routingtable/trie.go, routingtable/update_helper.go, routingtable/update_helper_test.go
- Deprecate Neighbor and PeerParams in favor of SessionAttrs
- Merge AddPathTX parameter of AdjRIBOut into SessionAttrs
- Split export checks for iBGP and eBGP paths
- Resolve some nits from go-staticcheck
- Remove internal duplication of attrs within AdjRIBIn
This superseeds #348 with a better name
=> Unify Neighbor and PeerParams in SessionAttrs and remove redundant variables

protocols/bgp/server/bmp_server.go
This is useful when listening on port 0 for testing purpose. We can
get the free port the kernel has allocated to us.
=> BMP: Add a method to get listener local address

cmd/ris/main.go, protocols/bgp/server/bmp_server.go
The previous `Listen()` function was more a `ListenAndServe()`
function and it triggers a race condition when calling `Close()`: call
it too early and you get a panic because the listener is not ready.
Just checking for `nil` in `Close()` would trigger another race
condition where the listener would not be stopped despite calling
`Close()` (because it was called too early).
=> BMP: separate Listen() and Serve() into two functions

net/ip.go, net/ip_test.go, net/prefix.go, net/prefix_cache.go, net/prefix_cache_test.go, net/prefix_test.go, protocols/bgp/server/bgp_api.go, route/bgp_path.go, route/route.go, route/static.go
We used to try do deduplicate IP addresses and prefixes as good as possible while doing so in a very controlled way.
This change rolls back the implicit deduplications happening in Prefix objects. I think in generals that we should handle IP addresses as plain objects whenever possible and only use pointers when we actually need the information to be deduplicated for memory efficiency reason. And that is actually only necessary in the routing tables. Path attributes are themselves deduplicated and to keep it simple we should not deduplicate the pieces that make up the path attributes.
=> Rework the IP datatype to be a value by default and change prefix to contain an IP and not a pointer

metrics/bgp/adapter/prom/bgp_prom_adapter.go, protocols/bgp/metrics/bgp_peer_metrics.go, protocols/bgp/server/metrics_service.go, protocols/bgp/server/metrics_service_test.go
The metrics »bio_bgp_up« is exposing the exact same value as the metric
»bio_bgp_state« having the value 6 so it adds redundant data to Prometheus
which becomes a concern at scale.
=> Remove redundant bio_bgp_up metric

net/ip.go, net/ip_test.go
It looks like Golang changed the behavior of the net.IP type with the latest
redesign, so that the address family cannot be determined anymore by looking
at the length of the underlying byte slice.  Adding two more tests to notice
any regressions early in the future.
=> Reflect Golang net.IP changes

cmd/ris/main.go, protocols/bgp/server/bmp_router.go, protocols/bgp/server/bmp_server.go, protocols/bgp/server/bmp_server_test.go
Until recently bio BMP accepted all UPDATEs regardless of pre of post
policy.  Commit 634c76c2540675e185dd6d044b49d55930fe2dc7 changed this
with the RIS use case in mind, but there are other use cases in which
we need to see pre-policy UPDATEs instead of even as well.  This commit
makes the behavior configurable, changing the default back to accepting
pre as well as post policy UPDATEs.
=> Allow configuring if pre-/policy UPDATEs should  be ignored

examples/bgp/ipv4.go, examples/bgp/ipv6.go, examples/bgp/main.go
The second IPv6 was missing the VRF line and the example was not working therefore.
I tried to simplify and streamline the example a little bit. This also removes the need for build tags to differentiate between IPv4 and IPv6.
=> fix: example bgp with v6 and cleanup

net/tcp/md5sig.go
On IPv6 the address starts later in on the struct-blob thing that is done inside buildTCPMD5Sig(), this was discovered after going down the rabbit hole with this code (I referenced this block in bgp.tools'es bgp daemon) with it not working on v6.
After comparing the output of strace for bird 2 and the output of this code, I realised the offsets were slightly different for IPv6, I assume this was already known since there was a branch that did the same thing for both address families
=> Fix IPv6 MD5 Password protected BGP sessions not working

protocols/bgp/server/peer.go
eBGP was broken because of this forgotten attribute.
=> fix: nil pointer for local address with ebgp

metrics/bgp/adapter/prom/bgp_prom_adapter.go
Fixing the label cardinality issue for metrics when a peer is established:
```
go run ./examples/bgp
INFO[0000] This is a BGP speaker                        
INFO[0000] Metrics are available :8080/metrics          
INFO[0000] Added BGP peer                                local_address=127.0.0.1 local_as=65200 peer_address=127.0.0.1 peer_as=65300
INFO[0000] Added BGP peer                                local_address="2001:678:1e0::cafe" local_as=65200 peer_address="2001:678:1e0::1" peer_as=65300
INFO[0000] Added BGP peer                                local_address="2001:678:1e0::cafe" local_as=65200 peer_address="2001:678:1e0:cafe::5" peer_as=65400
INFO[0009] Incoming TCP connection                       source="127.0.0.1:36775"
INFO[0009] FSM: Neighbor state change …
```
=> fix: metrics for bgp labels cardinality

cmd/bio-rd/main.go, cmd/ris-mirror/rismirror/router.go, protocols/bgp/server/bmp_router.go, routingtable/vrf/vrf.go, routingtable/vrf/vrf_registry.go, routingtable/vrf/vrf_test.go
If we only know the RD (because we only get the RD for BMP for example),  we use the human readable version of the RD as VRF name.
=> Index VRFs by name instead of RD

cmd/bio-rd/main.go, examples/bgp/main.go, protocols/bgp/server/fsm_address_family.go, protocols/bgp/server/metrics_service_test.go, protocols/bgp/server/server.go, routingtable/adjRIBIn/adj_rib_in.go, routingtable/session_attrs.go
RFC4277 Section 8. states that 100 is a - if not the - common value for Local Preference on eBGP sessions, where it would be 0 if none is set.  To increase interoperability with other BGP speakers we now allow setting a default value for Local Preference for the BGP server and default to 100 if none was set.
Closes #400
=> Allow setting default Local Preference for eBGP sessions and default it to 100.

cmd/riscli/dump_loc_rib.go, cmd/riscli/grpc.go, cmd/riscli/lpm.go, cmd/riscli/main.go, cmd/riscli/observe_rib.go
With this PR, the logging is adjusted to the new bio log util (and working again).
Also, all riscli grpc dialups are extracted to a common function. Support for Server-Side TLS is added.
=> riscli fix logging and allow encrypted grpc

cmd/ris-mirror/rismirror/router.go
VRFs for RIS-Mirror were not created with the correct name, this MR fixes that.
=> Fix VRF creation in ris-mirror

cmd/ris-mirror/rismirror/router.go, cmd/ris-mirror/rismirror/vrf.go
It was unclear in the RIS mirror which member of the `Router` object is authoritative regarding the VRFs.
The idea is to make the local map authoritative on existing VRFs. The `vrf.VRFRegistry` is only used to pass it to the metrics package to provide metrics.
=> RIS-Mirror: Refactoring

cmd/ris-mirror/rismirror/rismirror.go, cmd/ris-mirror/rismirror/router.go, cmd/ris-mirror/rismirror/vrf.go
When using the ris-mirror API, it was only possible to add new VRFs, but not remove vrfs from the ris-mirror at runtime.
This leads to problems when for example an vrf/router is not available any longer, but cannot be removed from the ris-mirror, leading to failing observeRIB calls.
This PR adds basic support for gracefully removing an router/VRF at runtime.
=> ris-mirror: Add API for removing one or all vrf ris clients at runtime

go.mod, go.sum, net/tcp/md5sig.go
Use the TCPMD5Sig type and its corresponding SetsockoptTCPMD5Sig helper added in x/sys v0.6.0 to set the TCP MD5 sig on a socket.
=> net/tcp: use SetsockoptTCPMD5Sig from golang.org/x/sys/unix

net/tcp/listen.go, net/tcp/tcpsock_posix.go, net/tcp/tcpsock_posix_test.go
=> BGP: Fix IPv4 listen addr configuration

cmd/bio-rd/bgp.go, cmd/bio-rd/config/bgp.go, cmd/bio-rd/config/bgp_test.go, cmd/bio-rd/main.go, docker/bio-rd/Dockerfile
This PR tries to improve the bio-rd BGP configuration.
It aims to provide the basic capability to run bio-rd in the current state after checking out supporting most out of the current feature set.
This is work in progress and thus only a draft for now.
In detail:
* adds IPv6 support
* improve readability
* encapsulate BGP server configuration
* allow to change BGP listen address
* respect configured VRF
* add group / neighbor inheritance for AFI specific configurations
* add tests for BGP config loading
=> bio-rd BGP configuration refactoring

.github/workflows/tests.yml, .gitignore, Makefile, README.md, cmd/bio-rd/bio-rd.yml, scripts/build_examples.sh
This is intended as the first step to lower the bar of entry on using Bio-Routing :-)
* Add a `Makefile` to build Bio-Routing commands and examples & test the code
* Update GitHub workflows to use make targets
* Update README to point out how to build and run `bio-rd`
* Some clean-ups
A good next step would be to start populating `Documentation/user` a bit more on more example configurations and how to use `bio-rd` and `bio-rdc` together.
=> Lower the bar on building Bio-Routing

metrics/bgp/adapter/prom/bgp_prom_adapter.go
Uptime metric was incorrectly calculated, this fixes is by calling `Seconds()` method on the duration.
=> Fix uptime metric

net/tcp/listen.go, net/tcp/listener_manager.go, protocols/bgp/server/server.go, tests/bgp_integration_test.go
Enable SO_REUSEPORT on the TCP socket,
This enables multiple instances of the BGP server to be started on the same machine, binding to the same TCP port.
The kernel will load-balance the incoming connections to all listening instances.
Instances that have the correct BGP peers configured will take the connection,
and those who don't will reject it, letting another instance have a try when the router restarts the connection.
=> Enable SO_REUSEPORT

.github/workflows/tests.yml
Codecov is heavily rate limited these days. For an org like bio it would cost us 5$ per month and user. Gotta look for an alternative. Dropping until then.
=> Fix CI by dumping codecov and upgrade go

RFCs.md, protocols/bgp/server/fsm_open_sent.go, protocols/bgp/server/peer.go
RFC6286, Autonomous-System-Wide Unique BGP Identifier for BGP-4, loosens the
requirements for Router IDs to allow for IPv6-only setups.
=> BGP: Implement RFC6286

protocols/bgp/packet/decoder.go, protocols/bgp/packet/decoder_test.go
Fixes [#488](https://github.com/bio-routing/bio-rd/issues/488)
=> isValidIdentifier() doesn't conform to rfc6286

.github/workflows/tests.yml, cmd/bio-rd/main.go, fuzzing/packet/gen_initial_corpus.go, go.mod, go.sum, protocols/bgp/packet/decoder.go, protocols/bgp/packet/decoder_test.go, protocols/bgp/server/fsm_open_sent.go, protocols/bgp/server/update_sender.go
Moved checkes for zero BGP identifier into OPEN message validation function and updated tests accordingly.
Also update to Go 1.23, as required by included packages.
=> Fix OPEN message tests wrt RFC6286 & update to Go 1.23
