bio-routing/bio-rd

net/prefix.go
net/prefix_test.go
route/bgp.go
route/bgp_path_manager.go
route/path.go
route/route.go
route/route_test.go
route/static.go

I'm reimplementing route and routetable entirely. This is intended to break the old route table. More PR's with new routetable implementation will come.

Added new route type and refactored net.Prefix

---

main.go
protocols/bgp/server/fsm.go
protocols/bgp/server/server.go
routingtable/adjRIBIn/adj_rib_in.go
routingtable/adjRIBOut/adj_rib_out.go
routingtable/adjRIBOutAddPath/adj_rib_out_add_path.go

This has the benefit that a user can controll the amount of logs printed to STDOUT.

Feature: Use logrus everywhere instead of fmt.Printf

---

protocols/bgp/packet/bgp.go
protocols/bgp/packet/decoder_test.go
protocols/bgp/packet/path_attributes.go
protocols/bgp/server/fsm.go

Feature: support AS4path and AS4aggregator ( RFC 6793 )

---

main.go
protocols/bgp/packet/bgp.go
protocols/bgp/packet/decoder_test.go
protocols/bgp/packet/large_community.go
protocols/bgp/packet/path_attributes.go
protocols/bgp/packet/path_attributes_test.go
protocols/bgp/server/bgp_update.go
protocols/bgp/server/fsm.go
protocols/bgp/server/update_sender.go
protocols/bgp/server/update_sender_add_path.go
route/bgp.go
routingtable/filter/actions/add_large_community_action.go
routingtable/filter/actions/add_large_community_action_test.go
routingtable/filter/large_community_filter.go
routingtable/filter/term_condition.go
routingtable/filter/term_condition_test.go

* receiving large communities
* sending large communities
* adding large communities by filter
* filtering for exact large communities

BGP large community support

---

routingtable/contributing_asn_list_test.go

Signed-off-by: Maximilian Wilhelm <max@sdn.clinic>

Add more tests for contributing ASNs.

---

README.md

Signed-off-by: Maximilian Wilhelm <max@sdn.clinic>

Respect and robustness! <3

---

protocols/bgp/server/fsm_established.go
route/bgp_path.go
routingtable/adjRIBOut/adj_rib_out.go

- Store if a route was learned from an eBGP or iBGP neighbor
- Print if route was learned from eBGP or iBGP and show route source in dotted format
- Add eBGP vs. iBGP check to tie breaking algo in route selection

Unfuck iBGP vs. eBGP handling

---

route/bgp_path.go

Signed-off-by: Maximilian Wilhelm <max@sdn.clinic>

BGPPath.insertNewASSequence() should extend the path in place.

---

protocols/bgp/server/peer.go
protocols/bgp/server/server_test.go

This information is useful for monitoring and debugging.

Added a states slice to peer info.

---

net/ip.go
net/ip_test.go

String to BIO IP Parsing

---

protocols/bgp/packet/mp_reach_nlri.go
protocols/bgp/packet/mp_unreach_nlri.go
protocols/bgp/packet/path_attributes_test.go

* added some boundary checks
Thanks to @hikhvar for the fuzzing tests discovering this problem
This PR resolves #102 #103 #104

Increased Multi Protocol decoding robustness

---

CONTRIBUTORS
Gopkg.lock
README.md

Also update vendoring and adding myself to CONTRIBUTORS.

Fix README after bazel remove

---

config/server.go
config/server_test.go

Mostly testing out my environment. Added some test cases and a comment as we're missing a lot of these...

My first commit

---

config/server.go
config/server_test.go

Added two tests for v6 addresses and switched the compare method from string compare to byte compare.

Add v6 test and switch compare method

---

util/decoder/decoder_test.go

increased test coverage of decoder

---

net/prefix_test.go

increased test coverage

---

protocols/bgp/server/fsm_address_family.go
protocols/bgp/server/fsm_address_family_test.go
protocols/bgp/server/update_sender.go
protocols/bgp/server/update_sender_test.go
protocols/fib/reader_linux.go
routingtable/adjRIBIn/adj_rib_in.go
routingtable/adjRIBOut/adj_rib_out.go
routingtable/client_interface.go
routingtable/client_manager.go
routingtable/client_manager_test.go
routingtable/locRIB/loc_rib.go
routingtable/mock_client.go

Fix FSM Address Family Init

---

protocols/bgp/types/as_path.go

Functionality is needed for Flowhouse where IP flows are annotated with src/dst ASN.

Add convenience functions for AS Paths

---

net/ip_test.go

This tests the code **the way it behaves right now**, without any modification. I assume it is correct, but I'm asking you to take good attention during the review. This one seems to be straight forward, but I will submit more PRs I'll need a little bit of help with 😬

Add test for IPv4FromBytes

---

RFCs.md
cmd/ris/config/config.go
cmd/ris/main.go
cmd/ris/ris_config.yml
examples/bmp/main_bmp.go
protocols/bgp/server/bmp_router.go
protocols/bgp/server/bmp_server.go
protocols/bgp/server/bmp_server_test.go

Hey, I had a usecase for a passive BMP connection (e.g. the router should initiate the TCP connection).
I tried to add it to the best of my understanding of the inner workings of bio-rd.
I am not sure how to add a unit test for it though.
Side-note: one of the existing test cases is failing even on master (TestFSMAFIInitDispose).

add passive mode for BMP

---

cmd/riscli/dump_loc_rib.go

This implements the #309 feature in the riscli tool.

add rib filtering options to riscli

---

route/bgp_path.go
route/bgp_path_test.go

IGP and Incomplete cases are mixed up for string and print.

fix BGPPath Origin cases for string and print

---

cmd/bio-rd/main.go
protocols/isis/server/lsdb.go
protocols/isis/server/lsdb_entry.go
protocols/isis/server/net_ifa.go
protocols/isis/server/net_ifa_rx.go
protocols/isis/server/server.go

Implementing ISIS LSP RX functionality.

Implement LSP RX handling

---

protocols/bgp/server/bmp_server.go

Signed-off-by: Maximilian Wilhelm <maximilian@cloudflare.com>

Fix nil pointer dereference in BMP server

---

protocols/bgp/packet/bgp.go
protocols/bgp/packet/path_attributes.go
protocols/bgp/server/fsm_address_family.go
protocols/bgp/server/fsm_established.go
protocols/bgp/server/update_sender.go

Just some housekeeping, to be merged after BGP Role PR

MP_(UN)REACH_NLRI are BGP Path Attributes

---

.github/workflows/tests.yml

Signed-off-by: Maximilian Wilhelm <maximilian@cloudflare.com>

Update go version to 1.19

---

cmd/ris/config/config.go
cmd/ris/main.go
protocols/bgp/server/bmp_router.go
protocols/bgp/server/bmp_server.go
protocols/bgp/server/bmp_server_test.go

Not sure yet if I really want this.

BMP: Allow ignoring BGP sessions based on peer ASN

---

cmd/ris/main.go
cmd/ris/risserver/server.go
examples/bmp/main_bmp.go
metrics/bmp/adapter/prom/bmp_prom_adapter.go
protocols/bgp/server/bmp_metrics_service.go
protocols/bgp/server/bmp_receiver.go
protocols/bgp/server/bmp_receiver_test.go

This is a preparation to implement a BMP sender :)

Rename BMP Server to BMP receiver in preparation for BMP Monitoring Station support

---

protocols/bgp/server/bmp_router.go

Wondering if we should only increase the counters for Peer Up/Down messages when we are not ignoring the messages, or add another counter for ignored messages, maybe even per Up/Down/Monitoring..? The latter would create a lot of new metrics though and would defy scale.

Reflect if a BMP Peer Up/Down message has been ignored in the logs

---

protocols/bgp/server/fsm.go
protocols/bgp/server/fsm_idle.go

After the reconnectInterval even the passive connection side tried reconnecting.

fix: do not reconnect bgp from passive side

---

cmd/riscli/main.go
cmd/riscli/routers.go

This PR allows riscli users to get all available routers with their vrfs.

riscli: Add "get routers" feature

---

cmd/ris-mirror/rismirror/router.go

The same Mutex was tried to Lock twice on removal of a VRF.

fix: deadlock in ris-mirror vrf removal
